apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-pesbuk
spec:
  selector:
    matchLabels:
      run: php-pesbuk
  replicas: 2
  template:
    metadata:
      labels:
        run: php-pesbuk
    spec:
      containers:
      - name: php-pesbuk
        image: aushafy/pesbuk:v1
        ports:
          - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: p-secret-fb
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: p-secret-fb
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: p-secret-fb
              key: DB_PASS
